import { EcosystemApp } from '@site/src/components/Ecosystem/EcosystemBlocks';

export const EcosystemAppsList: EcosystemApp[] = [
  {
    id: 1,
    name: 'Last One',
    description: 'Last one to bid before timer runs out takes the pot',
    icon: '/assets/ecosystem/last-one-icon.png',
    bgImage: '/assets/ecosystem/last-one-bg.png',
    bgGradientColor: '#E5B92A',
    tags: ['Gaming'],
    twitterId: 1037316970,
    href: 'https://last-bid.vercel.app/',
    titleColor: 'black',
    descriptionColor: 'black',
    tagsColor: 'black',
  },
  {
    id: 2,
    name: 'Ballsy',
    description: 'Battle for glory by logging in with your favorite chain',
    icon: '/assets/ecosystem/ballsy-icon.png',
    bgImage: '/assets/ecosystem/ballsy-bg.png',
    bgGradientColor: 'rgba(0, 0, 0, 0.80)',
    tags: ['Gaming'],
    twitterId: 1037316970,
    href: 'https://ballsy.push.org/',
    textColor: 'black',
  },
  {
    id: 3,
    name: 'Hodl.fun',
    description: 'Create & launch ERC-20 tokens',
    icon: '/assets/ecosystem/hodl-fun-icon.png',
    bgImage: '/assets/ecosystem/hodl-fun-bg.png',
    bgGradientColor: 'rgba(0, 0, 0, 0.80)',
    tags: ['DeFi'],
    twitterId: 1037316970,
    href: 'https://www.thehodl.fun/',
    textColor: 'white',
  },
  {
    id: 4,
    name: 'Bountive',
    description: 'Universal growth engine rewarding quality over clicks',
    icon: '/assets/ecosystem/bountive-icon.png',
    bgImage: '/assets/ecosystem/bountive-bg.png',
    bgGradientColor: '#000000',
    tags: ['Social'],
    twitterId: 1037316970,
    href: 'https://bountive.vercel.app/',
    textColor: 'black',
  },
  {
    id: 5,
    name: 'APT Casino',
    description: 'Universal, fair, & transparent wager to win',
    icon: '/assets/ecosystem/apt-casino-icon.png',
    bgImage: '/assets/ecosystem/apt-casino-bg.png',
    bgGradientColor: '#5E1140',
    tags: ['Gaming'],
    twitterId: 1037316970,
    href: 'https://apt-casino-push-chain.vercel.app/',
    textColor: 'white',
  },
  {
    id: 6,
    name: 'Push Ninja',
    description: 'On-chain skill based game',
    icon: '/assets/ecosystem/push-ninja-icon.png',
    bgImage: '/assets/ecosystem/push-ninja-bg.png',
    bgGradientColor: '#591D5C',
    tags: ['Gaming'],
    twitterId: 1037316970,
    href: 'https://push-ninja.vercel.app/',
    textColor: 'white',
  },
  {
    id: 7,
    name: 'OnchainVampireSurvivors',
    description: 'Universal vampire survivors like game',
    icon: '/assets/ecosystem/onchain-vampires-icon.png',
    bgImage: '/assets/ecosystem/onchain-vampires-bg.png',
    bgGradientColor: '#5D261E',
    tags: ['Gaming'],
    twitterId: 1037316970,
    href: 'https://catkevin.github.io/OnchainVampireSurvivors/',
    textColor: 'white',
  },
  {
    id: 8,
    name: 'TipUp',
    description: 'Tip on any chain using any wallet',
    icon: '/assets/ecosystem/tip-up-icon.png',
    bgImage: '/assets/ecosystem/tip-up-bg.png',
    bgGradientColor: '#000000',
    tags: ['DeFi'],
    twitterId: 1037316970,
    href: 'https://tip-up-push.vercel.app/',
    textColor: 'white',
  },
  {
    id: 9,
    name: 'ChainCircle',
    description: 'Cross chain saving circles',
    icon: '/assets/ecosystem/chaincircle-icon.png',
    bgImage: '/assets/ecosystem/chaincircle-bg.png',
    bgGradientColor: '#000000',
    tags: ['DeFi'],
    twitterId: 1037316970,
    href: 'https://www.chaincircle.org/',
    textColor: 'white',
  },
  {
    id: 10,
    name: 'EON: AI Butler',
    description: 'Send, swap, and manage assets across supported networks',
    icon: '/assets/ecosystem/eon-icon.png',
    bgImage: '/assets/ecosystem/eon-bg.png',
    bgGradientColor: '#000000',
    tags: ['NFT'],
    twitterId: 1037316970,
    href: 'on-five.vercel.app',
    textColor: 'white',
  },
  {
    id: 11,
    name: 'Degen Chess',
    description: 'Play chess, wager, universal',
    icon: '/assets/ecosystem/degen-chess-icon.png',
    bgImage: '/assets/ecosystem/degen-chess-bg.png',
    bgGradientColor: 'rgba(148, 163, 184, 0.25)',
    tags: ['Gaming'],
    twitterId: 0,
    href: 'https://degenchess.example.com/',
    textColor: 'white',
    comingsoon: 'true;',
  },
  {
    id: 12,
    name: 'Hang4.fun',
    description: 'Coming Soon',
    icon: '/assets/ecosystem/hangfun-icon.png',
    bgImage: '/assets/ecosystem/hangfun-bg.png',
    bgGradientColor: 'rgba(148, 163, 184, 0.25)',
    tags: ['TBA'],
    twitterId: 0,
    href: 'https://hang4.fun/',
    textColor: 'white',
    comingsoon: 'true;',
  },
];
