import { EcosystemApp } from '@site/src/components/Ecosystem/EcosystemBlocks';

export const EcosystemAppsList: EcosystemApp[] = [
  {
    name: 'Sushi',
    description: 'Multi-chain DEX & aggregator',
    icon: '/assets/ecosystem/sushi.png',
    bgImage: '/assets/ecosystem/sushi-bg.jpg',
    bgGradientColor: 'rgba(168, 85, 247, 0.35)',
    tags: ['DeFi', 'Infra'],
    twitterId: 1037316970,
    href: 'https://sushi.com/',
    textColor: 'black',
  },
  {
    name: 'MetaMask',
    description: 'Wallet',
    icon: '/assets/ecosystem/metamask.png',
    bgImage: '/assets/ecosystem/metamask-bg.jpg',
    bgGradientColor: 'rgba(251, 146, 60, 0.35)',
    tags: ['Wallet'],
    twitterId: 18015251,
    textColor: 'black',
  },
  {
    name: 'Token BulkSender',
    description: 'Bulksend tokens & NFTs',
    icon: '/assets/ecosystem/bulksender.png',
    bgImage: '/assets/ecosystem/bulksender-bg.jpg',
    bgGradientColor: 'rgba(59, 130, 246, 0.35)',
    tags: ['DeFi', 'Infra'],
    twitterId: 124567890,
    textColor: 'black',
  },
  {
    name: 'Ultiverse',
    description: 'AI-driven procedural content generation',
    icon: '/assets/ecosystem/ultiverse.png',
    bgImage: '/assets/ecosystem/ultiverse-bg.jpg',
    bgGradientColor: 'rgba(147, 197, 253, 0.35)',
    tags: ['Gaming'],
    twitterId: 987654321,
    textColor: 'black',
  },
  {
    name: 'Rocket Xchange',
    description: 'Multi-chain digital asset transfer',
    icon: '/assets/ecosystem/rocketx.png',
    bgImage: '/assets/ecosystem/rocketx-bg.jpg',
    bgGradientColor: 'rgba(190, 242, 100, 0.30)',
    tags: ['DeFi'],
    twitterId: 678901234,
    textColor: 'black',
  },
  {
    name: 'Cult of the Lamb',
    description: 'AI-driven procedural content generation',
    icon: '/assets/ecosystem/cotl.png',
    bgImage: '/assets/ecosystem/cotl-bg.jpg',
    bgGradientColor: 'rgba(244, 63, 94, 0.30)',
    tags: ['Gaming'],
    twitterId: 456789012,
    textColor: 'black',
  },
  {
    name: 'Coming Soon',
    description: 'More universal apps are on the way',
    icon: '/assets/ecosystem/coming-soon.png',
    bgImage: '/assets/ecosystem/coming-soon-bg.jpg',
    bgGradientColor: 'rgba(148, 163, 184, 0.25)',
    tags: ['TBA'],
    twitterId: 0,
    textColor: 'black',
  },
];
